### ISSUE TITLE
spattie role

### ISSUE THREAD

**Issue by TajulMunandar** [TajulMunandar/Sppd#5]
bang muk, ini kita engga terapin spattie role lagi ya?, banyak permission yang perlu di ubah kayanya

**Comment by mukhlizar16** [comment]
Iya, kita pake Laratrust Laravel roles and permission package.
https://laratrust.santigarcor.me/

**Comment by mukhlizar16** [comment]
> Iya, kita pake Laratrust Laravel roles and permission package. https://laratrust.santigarcor.me/

Atau tetap pake Spatie juga boleh.
